# Generated by Django 3.2.8 on 2021-10-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='wheather',
            new_name='weather',
        ),
    ]
